### ISSUE TITLE
Update DNS for activitystrea.ms

### ISSUE THREAD

**Issue by willnorris** [activitystreams/website#12]
Message displayed on https://github.com/activitystreams/website/settings: 

> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

Who owns the domain at this point?  @chrismessina I suspect?  Can you update the DNS entries?

/cc @activitystreams/core in case someone else has access.

**Comment by chrismessina** [comment]
I do. I'll take care of this.

—

*Chris Messina*

Founder  ◦  Speaker  ◦  Product Designer  ◦  Consultant
Previously: Google, Uber, Y Combinator W'18

instagram ( https://instagram.com/chris ) // twitter ( https://twitter.com/@chrismessina ) // linkedin ( https://linkedin.com/in/factoryjoe/ ) // product hunt ( https://www.producthunt.com/@chrismessina ) // web ( https://chrismessina.me )

**Comment by chrismessina** [comment]
Also, this seems out of date as well?

—

*Chris Messina*

Founder  ◦  Speaker  ◦  Product Designer  ◦  Consultant
Previously: Google, Uber, Y Combinator W'18

instagram ( https://instagram.com/chris ) // twitter ( https://twitter.com/@chrismessina ) // linkedin ( https://linkedin.com/in/factoryjoe/ ) // product hunt ( https://www.producthunt.com/@chrismessina ) // web ( https://chrismessina.me )

**Comment by chrismessina** [comment]
Ok, I've updated the DNS and verified the domain — so I'll also be adding HTTPS in the next day.

—

*Chris Messina*

Founder  ◦  Speaker  ◦  Product Designer  ◦  Consultant
Previously: Google, Uber, Y Combinator W'18

instagram ( https://instagram.com/chris ) // twitter ( https://twitter.com/@chrismessina ) // linkedin ( https://linkedin.com/in/factoryjoe/ ) // product hunt ( https://www.producthunt.com/@chrismessina ) // web ( https://chrismessina.me )

**Comment by willnorris** [comment]
Thanks, @chrismessina!
